--liquibase formatted sql

--changeset Osmanov:1
create table if not exists users
(
    id         integer generated by default as identity
    primary key,
    age        integer
    constraint users_age_check
    check (age >= 0),
    created_at timestamp,
    created_by varchar(255),
    email      varchar(255),
    last_name  varchar(20),
    name       varchar(20),
    password   varchar(255)
    );

-- insert into users (age, email, last_name, name, password)
-- values (22, 'www@mail.ru', 'www', 'www', '$2a$12$iARIUdHb7z6gjkAkAwAMLOi1IuqxgUZX5b6J8Tn01XXMvuhxZdsyS');

alter table users
    owner to postgres;
--rollback DROP TABLE users;

--changeset Osmanov:2
create table if not exists roles
(
    id        integer generated by default as identity
    primary key,
    role_name varchar(255)
    );

-- insert into roles (id, role_name)
-- VALUES (1, 'ROLE_ADMIN');
-- insert into roles (id, role_name)
-- VALUES (2, 'ROLE_USER');

alter table roles
    owner to postgres;
--rollback DROP TABLE roles;

--changeset Osmanov:3
create table if not exists user_roles
(
    user_id integer not null
    constraint fkhfh9dx7w3ubf1co1vdev94g3f
    references users,
    role_id integer not null
    constraint fkh8ciramu9cc9q3qcqiv4ue8a6
    references roles,
    primary key (user_id, role_id)
    );

-- insert into user_roles (user_id, role_id)
-- VALUES (1, 1);
-- insert into user_roles (user_id, role_id)
-- VALUES (1, 2);

alter table user_roles
    owner to postgres;
--rollback DROP TABLE user_roles;

--changeset Osmanov:4
insert into users (age, email, last_name, name, password, created_at, created_by)
values (22, 'www@mail.ru', 'www', 'www', '$2a$12$iARIUdHb7z6gjkAkAwAMLOi1IuqxgUZX5b6J8Tn01XXMvuhxZdsyS', current_timestamp, SESSION_USER);
--rollback

--changeset Osmanov:5
insert into roles (id, role_name)
VALUES (1, 'ROLE_ADMIN');
insert into roles (id, role_name)
VALUES (2, 'ROLE_USER');
--rollback

--changeset Osmanov:6
insert into user_roles (user_id, role_id)
VALUES (1, 1);
insert into user_roles (user_id, role_id)
VALUES (1, 2);
--rollback
